### ISSUE TITLE
Cross-compilation fails due to sqlite3

### ISSUE THREAD

**Issue by jpillora** [anacrolix/torrent#124]
```
$ uname -s
Darwin
$ GOOS=linux go build -o /tmp/t
# github.com/mattn/go-sqlite3
../../../../mattn/go-sqlite3/tracecallback_noimpl.go:7: undefined: SQLiteConn
```

Any workarounds for this?

**Comment by anacrolix** [comment]
Possibly https://github.com/anacrolix/torrent/issues/115, I just didn't get around to pushing it.

**Comment by jpillora** [comment]
Might be too big a change though using bolt would still provide an embedded db while also being pure Go

**Comment by anacrolix** [comment]
Yeah moving to something that doesn't require cgo is superior. You want to contribute a bolt completion DB? The interface should be pretty straightforward, just replace the sqlite one. Otherwise I'll get around to it in a week or two.

**Comment by anacrolix** [comment]
Okay this should be good now. It's the default for file, and mmap backends, and with cmd/torrent.

**Comment by mischief** [comment]
@anacrolix it looks like the boltdb file at https://github.com/anacrolix/torrent/commit/5c5a26afedee70dc16adbd3e00bcec239f289a73#diff-a229ed4209b117df5e97c6c4c65def88R9 still imports sqlite with `_`. is that intentional? i also don't see any thing to stop linkage of the sqlite code, like `// +build !cgo`.

**Comment by anacrolix** [comment]
Thanks for catching those.
