### ISSUE TITLE
implement announce_peer RPC

### ISSUE THREAD

**Issue by nodirt** [anacrolix/torrent#133]
I am considering to use this library to implement a distributed content-addressed file cache in our internal network, isolated from the rest of the world. I've just noticed that anonunce_peer RPC is [not implemented](https://github.com/anacrolix/torrent/blob/fdf75d59c833a26dde9facbd564cb0a203ef07c2/dht/server.go#L305). Do I understand correctly that a network consisting only of nodes built using this library will not actually work because of this?

**Comment by axet** [comment]
syncthing.net?

**Comment by anacrolix** [comment]
Receiving an announce_peer is not handled, as I do not store data on the current DHT node implementation.  However it would only be a very small amount of work to add that.

You may also consider running your own tracker on an internal network, or to use PEX and a bootstrap node.

Let me know your thoughts, in the meanwhile, I might actually add a counter to track just how much announce_peer traffic I am receiving on my servers, to see if the surrounding code is all working correctly in order to go ahead and add that implementation.

**Comment by anacrolix** [comment]
I should mention that the other use for announce_peer, as a client, is the core functionality and use for the dht package. It's most definitely functional, and really quite effective.

**Comment by nodirt** [comment]
to be clear, the networks are isolated, they are security boundaries, so I prefer not to share trackers

**Comment by anacrolix** [comment]
@nodirt Can you comment on the state of this issue?

**Comment by nodirt** [comment]
This is not urgent for me (in fact my priorities changed), but I think documenting these fundamental limitations of DHT implementation is important. If
I didn't read code, I wouldn't learn about them.

**Comment by anacrolix** [comment]
Whoops this was completed in https://github.com/anacrolix/dht/commit/3a71864cece2ca2321c80065afc3ee334c185a57.
