### ISSUE TITLE
Webtorrent support

### ISSUE THREAD

**Issue by faddat** [anacrolix/torrent#138]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24250%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/anacrolix/torrent/issues/138)

Does this client by any chance support webtorrent?  

If no, anyone know of a go torrent solution that does?

thanks!

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $250.00)

- [<img src='https://avatars1.githubusercontent.com/u/4278113?v=4' alt='steelbrain' width=24 height=24> steelbrain](https://issuehunt.io/u/steelbrain) ($50.00)
- $200.00 have been anonymously funded.
### Submitted pull Requests
- [#393 Webtorrent support](https://issuehunt.io/r/anacrolix/torrent/pull/393)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/anacrolix/torrent/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by anacrolix** [comment]
Do you refer to https://github.com/feross/webtorrent ? Can you link to a spec on bittorrent clients interacting with webrtc clients?

**Comment by faddat** [comment]
Not offhand, but I'm happy to google for it.... 

To leverage existing WebRTC implementations a dedicated instance of a Chromium browser is used. This 'bridge' mediates communication between Vuze and WebTorrent peers.
For the original implementation see https://webtorrent.io/

....ouch.  

Maybe I can find better in the node.js?

**Comment by anacrolix** [comment]
That's as much as I found. If you found specifics in the node.js code, that may expedite adding support for this.

**Comment by faddat** [comment]
@feross

**Comment by feross** [comment]
Hey! We'd love to help make WebTorrent support happen here. We're working on a spec. I'll share here when it's complete. At the moment you can check out the following files, to see what's going on:

- client: https://github.com/feross/bittorrent-tracker/blob/e5812fdd29eef06e240e2522464a25098e394b52/lib/client/websocket-tracker.js
- server: https://github.com/feross/bittorrent-tracker/blob/e5812fdd29eef06e240e2522464a25098e394b52/server.js#L444-L573

To sum up what it would take to support this:

- webrtc library or bindings in Go
- websocket library

When a `ws://` or `wss://` tracker is detected, create a websocket connection to that server. There are a few extra announce message types to facilitate establishing webrtc connections `"offer"` and `"answer"`, but everything else is essentially the same.

Once connected to a peer over WebRTC, you can treat the remote peer exactly the same -- the wire protocol is exactly the same.

**Comment by faddat** [comment]
Referenced in: 

https://github.com/dawn-network/glogchain/issues/#10
https://github.com/dawn-network/glogchain/issues/#11

**Comment by mattlepacek** [comment]
Webtorrent support here would be amazing.  The current node.js implementations are limited by chromes implementation of webrtc causing cpu time to multiply with each torrent being seeded.  I'm interested in sponsoring Webtorrent support

**Comment by anacrolix** [comment]
I'll revisit this when there's a spec.

**Comment by KeizerDev** [comment]
Any updates on this?

**Comment by anacrolix** [comment]
No progress. There's no spec, and WebRTC is abysmal to work with.

**Comment by Sean-Der** [comment]
Hey @anacrolix !

I have been working on Go native WebRTC https://github.com/pions/webrtc and would love to get it to the point that you could use it!

It currently has full support for Audio/Video (send and recv) and I am maybe two weeks out from finishing DataChannels. We have ~5 developers involved, so things are moving pretty quick! If you are interested would love to chat/figure out what is most important to you. All the devs are on the Gophers slack in the #pion channel

**Comment by jimmywarting** [comment]
Grate work @Sean-Der

**Comment by anacrolix** [comment]
Any update @Sean-Der?

**Comment by Sean-Der** [comment]
@jimmywarting thank you!

----
@anacrolix Yea! DataChannels support landed in pion-WebRTC, you can check it out [here](https://github.com/pions/webrtc/tree/master/examples/data-channels) there is still plenty of work to do but 'it works'

I will track a crack at implementing it myself, there are probably bugs and would hate for you to have to deal with them. Will start a branch and drop it here

**Comment by backkem** [comment]
Quick update on pions/webrtc: we've finished implementing DTLS and plan to land it in master as soon as December 1st. This enables WebRTC in pure Go!

I reached out in chihaya/chihaya#388 for the tracker side of things.

Regarding the client side. It seems we need to:
1. Introduce a new Webtorrent network type and revise any logic that assumes a hard coded amount of networks.
1. Generalize the `Peer` struct so it can store Webtorrent peers alongside IP peers. The main difference is that they have a list of SDP offers instead of an IP+Port. 
1. Allow the `Client` to connect using these new type of peers. We have to choose between:
  - Passing these offers to the client as a address string like the current implementation.
  - Modifying the client to accept something more complex than just an address string. The Peer object itself for example.
1. Create a WebRTC `socket`. The Listener is likely the most tricky part. It seems you have to open a bunch of PeerConnections and advertise their offer via the websocket tracker. TBD if we can use [pions/dcnet](https://github.com/pions/dcnet) to handle the connection itself.
After that we should be able to pipe the Bittorrent protocol over the WebRTC `socket` as usual.
@anacrolix what are your thoughts on this? Am I missing any big steps? How would you favor to handle the Webtorrent peers alongside regular IP-based peers?

**Comment by Vladislavik** [comment]
Any news about suppert webrtc? It is https://github.com/gorilla/websocket
That work pretty with websockets on Go

**Comment by anacrolix** [comment]
@Vladislavik No news on WebRTC.

**Comment by jpillora** [comment]
https://github.com/pion/webrtc

> A pure Go implementation of the WebRTC API

**Comment by Sean-Der** [comment]
@jpillora I would love to see that happen :)

I wish I had the bandwidth to help, but I am always behind with `pion/webrtc`. If you start a PR I can answer any questions/make improvements that are need to make it happen.

**Comment by jpillora** [comment]
I also wish I had the bandwidth :P posting just in case we have any
generous volunteers

**Comment by anacrolix** [comment]
Does anyone have any numbers on the level of Webtorrent participation in the BitTorrent swarm? How about with alternative transports such as Websocket and QUIC? I could consider putting the time in to implement this myself if I know there's enough value in it.

**Comment by lgrahl** [comment]
WebSockets will not work in browsers as discussed in length in https://github.com/webtorrent/webtorrent/issues/1492. QUIC is interesting but it's just a trial at the moment. We will have to wait for [WebTransport](https://github.com/WICG/web-transport) to become widely available **and** support peer-to-peer. But then it is definitely something we should jump on, although WebTransport is and will not be limited to QUIC.

**Comment by lgrahl** [comment]
That being said, there's **zero reason to not go with pion/webrtc right now** since this is a Go implementation. You have no idea how privileged you are in the world of WebRTC to have this stack. Please, jump on it now. You can still try fancy new technology and APIs later.

**Comment by Sean-Der** [comment]
Thanks @lgrahl :) 

@feross do you have any numbers around WebTorrent participation? @anacrolix I think you are in a really unique position to create the best WebTorrent client. 

Everyone else is stuck doing Electron/Chromium if you got it working it would be dramatically more performance/less costly. Could make a really big impact, also the portability of Go would be a huge improvement also.

**Comment by feross** [comment]
WebTorrent Desktop has around **2,214,602** installs.

The browser version of `webtorrent` is a little bit harder to measure since folks can install it from `npm` and then ship it to millions of users potentially, and we'll just see that as a single installation in the npm stats. However, here's what we know:

- **9,400** downloads/month on npm
- **64 million** hits/month on the [CDN-hosted script bundle](https://cdn.jsdelivr.net/npm/webtorrent@latest/webtorrent.min.js)

Community members who run a WebTorrent tracker server like @DiegoRBaquero, @alxhotel, or @jakefb may have additional stats that they can share about how many peers are online at any given time, but the WebTorrent project has no information about this since we do not run tracker servers.

**Comment by Sean-Der** [comment]
Those are some big numbers, nice work @feross!

Is it true what I said about no light weight clients being available? Everything requires Electron/Chromium?

**Comment by backkem** [comment]
Yes, all existing clients listed in webtorrent/webtorrent#369 use the JavaScript Webtorrent implementation under the hood. Libtorrent would be the other major implementation but they are struggling with picking a WebRTC lib since they all have tradeoffs. I think we don't have that problem. Pion WebRTC is a clean and stabilizing implementation and it will be easy to get any issues we run into addressed. The biggest work, aside from the missing spec (which isn't that complex), will be around instrumenting the peers that have different data and behavior associated with them as I described above.

**Comment by backkem** [comment]
In order to kick this off I started on super bare bones port over at [backkem/gowttest](https://github.com/backkem/gowttest). It's not meant to become a client, just an example. It can currently connect to the websocket tracker, advert a WebRTC offer and receive answers (not parsed yet). With a little imagination this solves most of the missing spec problem. I'll keep working on it sporadically but I sadly don't have much spare time ATM. Feel free to ask questions, create PRs (let me know via issue/WIP PR) or take the code and run with it.

**Comment by anacrolix** [comment]
Thank you @backkem! This should be enough for me to go on.

**Comment by Sean-Der** [comment]
@anacrolix What can I do to help with this coding wise or answering questions? Would funding be helpful at all?

My motivation is just getting more people using Pion. The more people using it the more bug reports and all that great stuff :)

**Comment by anacrolix** [comment]
@Sean-Der it's a matter of time and motivation at the moment. Funding will always help.

**Comment by backkem** [comment]
Libtorrent is also working on this in arvidn/libtorrent#4123. I may provide some extra inspiration.

Can we fix the labels on this? It seems neither blocked or waiting for feedback at this point.

**Comment by anacrolix** [comment]
A spec would still be nice, but otherwise I think everything needed is now available. Changes related to https://github.com/anacrolix/torrent/issues/356 will overlap with this somewhat.

**Comment by anacrolix** [comment]
I'm still happy to implement this with appropriate funding. It's several weeks of work.

**Comment by vijayanandnandam** [comment]
@anacrolix can you open a patreon funding campaign to fund this? I would be happy to fund some, but may not be able to fund the entire effort. It will also show how many are interested in getting this implemented

**Comment by nektro** [comment]
@vijayanandnandam there is one: https://patreon.com/anacrolix

**Comment by Sean-Der** [comment]
@anacrolix sorry for the delay

Would you mind do something that allows single donations/has a set goal? I have a few people who have offered to pay for Pion work, and I would love to redirect them to your GoFundMe/Patreon/X!

When you have that I am going to push the Pion community towards it! I will put it on Twitter/Pin on Slack and donate myself, see what we can make happen :)

**Comment by anacrolix** [comment]
@vijayanandnandam I have Patreon, Liberapay, and GitHub Sponsors, you can view that stuff at the top of the project page when you click the Sponsor button.

@Sean-Der I've created https://issuehunt.io/r/anacrolix/torrent/issues/138, I think that should work? I'm open to suggestions.

Thanks to @backkem for his existing sponsorship.

Sorry everyone else for the noise.

**Comment by Sean-Der** [comment]
@anacrolix and there it is :)

If you hit any bugs/have questions we are in [Slack](https://pion.ly/slack) and would love to help. I am sure you will hit some roadblocks along the way, but will do my best to unblock you!

**Comment by anacrolix** [comment]
@Sean-Der thanks.

**Comment by anacrolix** [comment]
The Dialer and Listener interfaces have been abstracted out in #380, which is the first step toward implementing this. I've created https://github.com/anacrolix/torrent/milestone/2 to track any issues and PRs that progress this issue.

**Comment by Sean-Der** [comment]
Anything I can do to help @anacrolix ? Happy to get involved with any of the WebRTC stuff.

**Comment by anacrolix** [comment]
@Sean-Der I've created issues the next 2 items we need. I think it may be possible to do them concurrently, so long as the `addr string` is agreed upon by the tracker and Dialer implementations.

**Comment by anacrolix** [comment]
I did some more investigating. This looks exceptionally difficult to integrate into the existing code. The tracker and connection management are tightly coupled. It's also probably not appropriate just to maintain state at the Torrent level for trackers, it might be necessary at the Client level in order to scale to many Torrents with the same tracker URLs specified. The potential for disconnection from the trackers is a real kicker, I think there will be need to be many events flowing around the system.

**Comment by backkem** [comment]
I think disconnecting form the tracker isn't the end of the world. Once established, the WebRTC connections don't need the tracker's Websocket connection to stay alive.
However, losing the connection before signaling is complete does mean you won't be able to complete the setup of a WebRTC connection.

Managing the tracker Websocket connections globally is probably a good idea since they will have more overhead than regular UDP ones.

**Comment by backkem** [comment]
The WebRTC connection setup is likely even more tricky. Normally WebRTC will allocate random ports for both sides of the connection. In addition, there are two steps: signaling (tracker) and the actual connections (torrent). This would require a bunch of back-and-fort between the tracker and connection logic and it's quite inefficient for this use-case.

However, unlike in the browser we have more control over the network stack. You could potentially address these downsides as follows:
* Create an offer with one IP and a random port (Potentially without actually allocating it but that creates a risk that it will be taken later..) and a random certificate.
* Announce it to the tracker.
* Create answers for incoming offers by always using one IP and the same port but different certificates.
* Send it to the tracker.
* Listen on that one port for incoming connections.
* When a connection comes in, identify it by looking up the IP & certificate in the offers you received. (This may require some DTLS trickery..)
* Establish the connection.

This would mean:
* Decent separation between tracker & torrent connection logic.
* Reduced need to pro-actively open a bunch of listening ports.

The pion/webrtc library should be flexible enough to make this happen.

**Comment by anacrolix** [comment]
Thanks for the assistance again @backkem. I have a in-progress branch at https://github.com/anacrolix/torrent/tree/webtorrent that's able to download. Within the `torrent` repo, you can test it with `GOPPROF=http go run -race -v ./cmd/torrent -dht=false 'magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=wss://tracker.btorrent.xyz&tr=wss://tracker.fastcast.nz&tr=wss://tracker.openwebtorrent.com'`. It's very rough for now, but I'll continue to mold it to the `torrent` architecture, and take suggestions and improvements from people more familiar with WebRTC and webtorrent.

**Comment by anacrolix** [comment]
That command is now `$ GOPPROF=http go run -v ./cmd/torrent download -dht=false -tcpPeers=false -utpPeers=false 'magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=wss://tracker.btorrent.xyz&tr=wss://tracker.fastcast.nz&tr=wss://tracker.openwebtorrent.com'`.

**Comment by anacrolix** [comment]
I'm closing this as done. There are further improvements to be made, but now that Webtorrent is supported on master, those will come over time.

**Comment by jpillora** [comment]
Nice work Matt!
