### ISSUE TITLE
Why can't I download magnet?

### ISSUE THREAD

**Issue by Tyrone-Zhao** [anacrolix/torrent#326]
![image](https://user-images.githubusercontent.com/37615298/62786898-1e9f7a80-baf6-11e9-8d66-db86659b28b5.png)

As you can see, I use this from home. But can't download magnet. Should I take a indivisual IPv4 address or I can do this with 192.168.0.1? Where am I wrong?

**Comment by Tyrone-Zhao** [comment]
What should I do?

**Comment by anacrolix** [comment]
I believe I've discovered a long-standing bug introduced over a year ago, and subsequently fixed it. For popular torrents and users that aren't easily discoverable (such as behind NAT or similar), with slowish/high-latency connections, it's very difficult to establish outgoing connections. The bug is introduced by e3cb94006c3ac13fcef0a4699692b7191d2bb500 and fixed by 6013f09f8a7c3d96ae3e5bba5bff455467232029. Could you try with the fix and report back?

**Comment by Tyrone-Zhao** [comment]
Yes，I think so. the speed is very slow at begining. My environment is Fabic Adsl. Should I try it on clould like AWS？



发自我的iPhone


------------------ Original ------------------

**Comment by anacrolix** [comment]
Please try with the same connection as before, but with the fix.

**Comment by Tyrone-Zhao** [comment]
It works! But the speed is also slowly. XD

**Comment by Tyrone-Zhao** [comment]
could you change the imports such as golang/x/net to github.com/golang/net? I do this locally, but can't push to the respository. Thinks!

**Comment by Tyrone-Zhao** [comment]
but it works still slowly, how can I make it fast?

**Comment by Tyrone-Zhao** [comment]
I should say your code is very strong, after I reboot my network the program still work!

**Comment by Tyrone-Zhao** [comment]
It ia very fast this time. Oh it‘s really cool！XD



发自我的iPhone


------------------ Original ------------------

**Comment by anacrolix** [comment]
Thank you for reporting! Fixed in https://github.com/anacrolix/torrent/commit/6013f09f8a7c3d96ae3e5bba5bff455467232029.
