### ISSUE TITLE
Drop low-speed peers

### ISSUE THREAD

**Issue by procks** [anacrolix/torrent#362]
To maximize download speed, Is it possible (for slow devices) to limit the number of connections and drop low-speed peers?

**Comment by anacrolix** [comment]
Yes, this should already be the default. Connections are limited per `Torrent`, and efforts are made to drop the worst-performing peers when the connection limit is exceeded. Have you found the behaviour to be otherwise?

**Comment by anacrolix** [comment]
@procks do you have any more information?

**Comment by h31p** [comment]
let me give my 5 cents.

imagine the situation when we have only 2 peers, one extremely fast and one extremely slow. with right logics, we must have an overall speed not lower than faster one gives, but in practice - we don't get it, because loading pieces is half-interleaved in some strict manner between them, irrespective of their actually learned speeds of transfer.
the realtime analisys of such situation through PeerConn.writeStatus cycle shows periodically:
`
 1. "-TR2940-ki29rqcjndon"                                  0000000000100004 172.17.0.9:53524-172.17.0.8:50684
    last msg: 0.08s ago, connected: 162.88s ago, last helpful: 0.08s ago, itime: 2m38.220937492s, etime: 2m34.359138574s
    3675/3675 completed, 1 pieces touched, good chunks: 34486/36672-0 reqq: (256,351,512]-0, flags: i-eTr-, dr: 3487.3 KiB/s
    next pieces: [253 252]

 2. "-UT3120-\x81h8\x85n\x85+\x92\xb4\f>\a"                 0000000000100005 0.0.0.0:42069-Y.Y.Y.Y:55505
    last msg: 0.01s ago, connected: 1.23s ago, last helpful: 0.01s ago, itime: 1.151716782s, etime: 407.570837ms
    3675/3675 completed, 1 pieces touched, good chunks: 2/2-0 reqq: (32,62,64]-0, flags: i-eIU-, dr: 27.8 KiB/s
    next pieces: [252 253] (fastest)
`

172.17.0.8 here is a local bt seed on 1gbit network, second is slow seed from internet.
note, for that moment foreign peer, which is more than 100 times slower than another one - for some reason was selected as fastest. and they are doing permanent flip-flop dance for this place in dynamics, causing big dl speed drop - about just 4-6 MiB/s in that case.
in absence of internet peers - engine leeching from local with full speed, about 1gbit.
and such behavior is observed despite of request strategy selected (i.e. with any of them).

**Comment by anacrolix** [comment]
I see the confusion. The `(fastest)` tag on a connection is added if it was the most recent to upload a chunk to us. This is only used by the ["fastest" request strategy](https://pkg.go.dev/github.com/anacrolix/torrent?tab=doc#RequestStrategyFastest), which is not the default and probably not the one you are using. That strategy works by assuming whichever connection last uploaded a chunk to us is the fastest, and having it provide all the immediately pending data, while requesting low-priority data from all other connections. Due to the way request queues are managed, probable that the connection that's actually the fastest will elected when the queues are topped up. I can rename a bunch of this stuff, add comments, and improve the `(fastest)` tag if that would help.

**Comment by anacrolix** [comment]
Is there any more feedback for this? @h31p @procks
