### ISSUE TITLE
request: ClientConfig.OnPeerDiscovery(f func(t *Torrent, peers []Peer))

### ISSUE THREAD

**Issue by nektro** [anacrolix/torrent#373]

**Comment by nektro** [comment]
If accepted, I could work on this PR if you'd like.

**Comment by nektro** [comment]
This may also be better placed in `ClientConfig`.

**Comment by anacrolix** [comment]
Would this hook everything added from trackers, DHTs, PEX etc.?

**Comment by nektro** [comment]
Ideally.

**Comment by anacrolix** [comment]
What's the use-case?

**Comment by nektro** [comment]
Creating a client on top of `anacrolix/torrent` and being able to update the interface upon the event call.

**Comment by anacrolix** [comment]
What about polling each Torrent for the data points you want?

**Comment by anacrolix** [comment]
@nektro I'd like to support this, but need more information.

**Comment by nektro** [comment]
Polling would work as a work around in the event that this does not get accepted, but that method seemed much more resource intensive than being able to give the client a callback function.

**Comment by anacrolix** [comment]
What are the data points you want to show in your interface?

**Comment by anacrolix** [comment]
@nektro could you provide some more information?

**Comment by nektro** [comment]
> What are the data points you want to show in your interface?

> OnPeerDiscovery

the list of peers on a torrent

**Comment by nektro** [comment]
perhaps this could be added to torrent stats as well.

**Comment by anacrolix** [comment]
> > What are the data points you want to show in your interface?
> 
> > OnPeerDiscovery
> 
> the list of peers on a torrent

Do you mean like in a traditional torrent client GUI? You show the currently connected peers, and information about them? That's available via https://pkg.go.dev/github.com/anacrolix/torrent?tab=doc#Torrent.PeerConns.

**Comment by nektro** [comment]
right but this feature request was to be able to get that info in an event-driven way

**Comment by anacrolix** [comment]
@nektro I follow, I just wanted to clarify. Active peer changes would be a different event to peer discovery. Say a new connection is added, or a peer's available pieces change, would that be what you're after? I'm still leaning toward polling this, despite being in favour of event driven stuff in general: There's a huge amount of potential information to collect, and it changes very quickly. If you are notified of changes, without a full description of the new state included, the act of obtaining locks, and mapping all the state is delayed from the original notification anyway.

I've solved this in related projects by essentially having a flag indicating that state has changed since you last looked. You unset it before reading the state, and the client would set it again as soon as the state changes (thereby after you read the state and use it, you just look again at the flag, you will never miss anything).

There is a full-client sync.Cond that could be used, that would cover all cases, but as I mentioned above, it would become very expensive, very quickly.

**Comment by anacrolix** [comment]
I suspect that it is. Let me know if there's more feedback @nektro .
