### ISSUE TITLE
cmd/torrent: -testPeer no longer accepts string names

### ISSUE THREAD

**Issue by yarikk** [anacrolix/torrent#395]
Since recently,

```
% torrent download -dht'=false' '-testPeer=seed:44444' -stats -seed x.torrent
tagflag: error parsing args: parsing flag "testPeer=seed:44444": parsing value "seed:44444" for flag "testPeer": parsing host "seed": error parsing IP

```

Not sure if the change is in right direction: since BEP3 allows "An optional parameter giving the IP (or dns name) which this peer is at. " in tracker announcements, shouldn't test peers allow that too?

**Comment by anacrolix** [comment]
This is due to a [change I made in tagflag](https://github.com/anacrolix/tagflag/commit/26503342bd2ec719e24605f5e624b49f56c35785). I found that resolving hostnames was stalling argument parsing, which led to really weird behavior sometimes. I think the solution is to accept a string if you want to resolve it manually, or if you prefer the old behaviour, downgrade tagflag slightly or propose a better way to handle this.

**Comment by anacrolix** [comment]
Do you have any more feedback on this @yarikk? Can I close this?

**Comment by yarikk** [comment]
While it would be nice to have this consistent with what the _net.Dial_ would accept, it's definitely not critical.

**Comment by anacrolix** [comment]
Should be fixed, let me know if you have any issues.
