### ISSUE TITLE
Seeding a removed file causes sending garbage and eventually get banned by peers.

### ISSUE THREAD

**Issue by yarikk** [anacrolix/torrent#417]
If the file being seeded gets removed externally, the seeding keeps going, serving garbage to peers. The peers eventually ban the bad seeder.

The following code lets that happen:

https://github.com/anacrolix/torrent/blob/dd51e99b88ccd7afe8a361b5c5161cfeae6c9b7b/storage/file.go#L138
https://github.com/anacrolix/torrent/blob/dd51e99b88ccd7afe8a361b5c5161cfeae6c9b7b/peerconn.go#L1522

The ban is client-wide and spans across multiple torrents.

Switching to the _mmap_-based storage implementation helps but those conditionals worth revisiting: sending garbage is no good.

**Comment by anacrolix** [comment]
Sorry for the delay. Good catch! I think the correct behaviour here would be to always error if the bytes aren't filled entirely, and possibly to ignore the error otherwise?

**Comment by anacrolix** [comment]
I think I may have jumped to conclusions. If you delete the files externally, the torrent client will have no knowledge that the data is incorrect unless it tries to hash it it again. It will check that the file exists before trying to read, but if it's recreated the file for some reason (due to receiving a chunk), that check won't help.

Mmap probably handles the situation better, because deleting the files from the filesystem doesn't affect the mapped file data (the storage only mmaps at startup, and will continue to operate on the extents it mapped at that time, until the torrent client/storage is closed).

You shouldn't delete the files for the mmap or file storage implementations from underneath the torrent client, or if you do, make sure to run a full piece check afterward (there are some methods for this). If you delete mmap files, you will need to remap to the new files, or expect to continue on data that will disappear when the storage is closed. In all cases, you will also need to take care of the piece completion state, which may be on the disk (with the bolt implementation), or in memory.

It might help to know your use case, as if you're trying to do caching, another storage implementation, like the sqlite or filecache/piecePerResource implementations would be more appropriate.

@yarikk let me know if I've missed something, if my assumptions are wrong, this is a pretty serious bug.

**Comment by yarikk** [comment]
Mmap has saved the day because while the file is mapped the fd remains open, and upon unlink the reclamation of the underlying storage is deferred by OS until all fds referencing it are closed (unix behavior). The non-mmap backend opens/closes the file for each peace io, and the deferring does not happen.

Simply handle file read errors and treat then as an indication that the piece is not available. Short reads too. Pretending the error never happened is flawed.

Thanks for looking into this.

**Comment by anacrolix** [comment]
Thanks. Per-above I think it's not that errors are ignored (the chunk is only sent if all the requested data is read), but that the data as read, and the state that the torrent client think it's in are out of sync (the files are recreated lazily on writes).

So as far as I can tell, the code snippets you linked to are correct, assuming the behaviours I've described.

**Comment by anacrolix** [comment]
I'll tentatively close this as won't fix, as I don't see a clear fix with the current design (not to mention it would come with a lot more costs), and there are plenty of workarounds. Feel free to re-open if I've gotten this wrong.
