### ISSUE TITLE
Downloading torrent files to memory instead of disk

### ISSUE THREAD

**Issue by YenForYang** [anacrolix/torrent#426]
I'm asking about this [response on StackOverflow](https://stackoverflow.com/a/29034222/7314180) because of this [comment](https://stackoverflow.com/questions/6089806/keeping-the-downloaded-torrent-in-memory-rather-than-file-libtorrent#comment100929569_29034222)

To make sure this doesn't turn out to be an XY problem, I will state the issue I'm trying to solve.
I'm trying to download torrents and upload them to cloud (google drive/box) while skipping the writing to disk part entirely -- i.e. to more or less "stream" files to the cloud.
The ultimate goal would be to start an upload **before** an entire file is downloaded since any individual file could be too big to fit in memory (to keep memory usage of the files to be a few gigs max), but that isn't the primary issue right now.
For now, I think simply learning how to download any individual file in memory is enough -- *assuming* that streaming files to the cloud would use the same basic method.

I haven't found any way to do this through Google. I'm assuming that this Go library is easier to use than [libtorrent](https://github.com/arvidn/libtorrent) (C++) (implementing a [custom storage on libtorrent](https://libtorrent.org/reference-Custom_Storage.html) would be rather difficult)

**Comment by tabjy** [comment]
Hi @YenForYang,

I'm trying to do very similar things here. The difficulties here is to not storing large files in menory or on local disk. After playing around it turns out to be non-trivial. It might be helpful to look at the [`storage`](https://github.com/anacrolix/torrent/tree/master/storage) package and see how file-based [storage backend](https://pkg.go.dev/github.com/anacrolix/torrent/storage#ClientImpl) is implemented for an example.

The first challenge is to determine the file boundaries and gather which pieces are associated to which files. You can retrieve this information from the torrent metadata.

However, note that due to the nature of bt torrent protocols, pieces are not neccessarily downloaded sequentially. You might also want to take a look at Google Drive v3 API for [resumable uploads](https://developers.google.com/drive/api/v3/manage-uploads#resumable) which allows you to upload a large file one chunk at a time. I don't yet know whether those chunks can be uploaded in an arbitrary order. You need to experiment a bit.

Also, do realise for resumable uploads, each chunk (except the that) is at least 256kB, while the size of a BT piece varies for a torrent file. You might want to collect more consecutive pieces before uploading. This also reduces the change being rate limited.

Furthermore, my ideas assume you don't upload to other peers, ie. no seeding. Or you must read from Google Drive as well which further degrades the performance.

**Comment by anacrolix** [comment]
@YenForYang @tabjy's comments are spot on. You can do this with a custom storage backend implementation. You have the option to for example cache incomplete pieces in memory, store pieces instead of files, store everything on a cloud service etc. There are tradeoffs throughout. Caching things in memory is difficult, as depending on how many partial pieces or files you have, and how many torrents, you might not know how memory will be required, or when to evict things. Storing everything on the cloud from the get-go is also possible, but you will pay some performance costs there too.

**Comment by YouROK** [comment]
> I'm asking about this [response on StackOverflow](https://stackoverflow.com/a/29034222/7314180) because of this [comment](https://stackoverflow.com/questions/6089806/keeping-the-downloaded-torrent-in-memory-rather-than-file-libtorrent#comment100929569_29034222)
> 
> To make sure this doesn't turn out to be an XY problem, I will state the issue I'm trying to solve.
> I'm trying to download torrents and upload them to cloud (google drive/box) while skipping the writing to disk part entirely -- i.e. to more or less "stream" files to the cloud.
> The ultimate goal would be to start an upload **before** an entire file is downloaded since any individual file could be too big to fit in memory (to keep memory usage of the files to be a few gigs max), but that isn't the primary issue right now.
> For now, I think simply learning how to download any individual file in memory is enough -- _assuming_ that streaming files to the cloud would use the same basic method.
> 
> I haven't found any way to do this through Google. I'm assuming that this Go library is easier to use than [libtorrent](https://github.com/arvidn/libtorrent) (C++) (implementing a [custom storage on libtorrent](https://libtorrent.org/reference-Custom_Storage.html) would be rather difficult)

Im write service torrent to http, may be it help you
https://github.com/YouROK/TorrServer
storage implementation
https://github.com/YouROK/TorrServer/tree/master/src/server/torr/storage/memcache
