### ISSUE TITLE
Does it support DLP-alike function(Dynamic Leecher Protection)?

### ISSUE THREAD

**Issue by caryyu** [anacrolix/torrent#428]
I'm wondering how this library can prevent the un-trusted peers that only downloads without uploading through this protocol here? if someone can break my confusion up, i really appreciate..

**Comment by anacrolix** [comment]
By default, if `ClientConfig.Seed` is false, the client will upload only to encourage reciprocation from peers, to a point. See also the `DisableAggressiveUpload` field in `ClientConfig`. 

https://pkg.go.dev/github.com/anacrolix/torrent#ClientConfig

Please reference any leecher protection specs for BitTorrent that you're aware of so that I can address or implement them.

**Comment by caryyu** [comment]
@anacrolix thanks for reply, I guess this is what it is, but the mechanism behind these configs are still vague to me, anyway, i will go through the source code finding out, very appreciate :)

**Comment by anacrolix** [comment]
You'll want to check out `PeerConn.uploadAllowed`, and everything to which that refers.
