### ISSUE TITLE
Open/Close performance

### ISSUE THREAD

**Issue by gumanist** [anacrolix/torrent#45]
os: windows8 x64
go: master
code: https://github.com/anacrolix/torrent/blob/master/data/file/file.go#L73-L80
pprof: http://svgur.com/i/3X.svg
same torrent without Open/Close for each write:
http://svgur.com/i/2s.svg

**Comment by anacrolix** [comment]
I take it the mmap data implementation doesn't work for you on Windows?

**Comment by gumanist** [comment]
used example from here https://godoc.org/github.com/anacrolix/torrent 
file.TorrentData is used by default

as for mmap:
go get github.com/anacrolix/torrent/tree/master/cmd/torrent on windows gives:
go\src\launchpad.net\gommap\gommap.go:52: undefined: syscall.Stat_t
go\src\launchpad.net\gommap\gommap.go:58: undefined: mmap_syscall
etc
so i would use something like https://github.com/edsrzf/mmap-go :)

**Comment by anacrolix** [comment]
I've been meaning to switch to https://github.com/edsrzf/mmap-go for some time. I will accept a PR for this if you like, if switching fixes mmap for you on Windows. You are correct about the direct copy being possible, the way it currently is, is for easier abstraction. Given the size of pieces is usually 16KB, I doubt there's any improvement to be gained by reading directly from the socket into memory, especially since there's no guarantee that the entire 16KB is immediately available for a single copy operation. That ioutil.ReadAll line could probably be replaced with a b.Bytes() or something though.

I've gone with Open/Close on every operation in the file implementation because the alternative is to introduce arbitrary caching of file handles, or just switch to mmap. I'm open to ideas on this.

**Comment by anacrolix** [comment]
Could you confirm this now works for you?

**Comment by gumanist** [comment]
the CPU usage is still high 3x comparing to other command line client. will profile it eventually
