### ISSUE TITLE
Feature Request: Stop torrent at certain Seed ratio

### ISSUE THREAD

**Issue by gitpubber** [anacrolix/torrent#498]
It would be great to stop torrent at certain seed-ratio. or even stop torrent after certain bytes uploaded(after completion)

**Comment by gitpubber** [comment]
@anacrolix how would this be done? does this require extra goroutine which checks for seed ratio?

**Comment by anacrolix** [comment]
You'd want to watch BytesWrittenData and BytesReadUsefulData in https://pkg.go.dev/github.com/anacrolix/torrent#TorrentStats, and toggle the Seeding state appropriately. Since this could be done from external to the client if the ability to change the Seeding mode was exposed, I think it might be okay not to build this into the anacrolix/torrent implementation. It could be a contrib helper or something.

**Comment by gitpubber** [comment]
But, won't that be resource intensive?

**Comment by gitpubber** [comment]
@anacrolix it would be better if we could set max seed ratio (or max upload bytes) in Torrent Spec. Torrent Client before starting the download checks if these options have been set or not. if they are set,it launches another goroutine which stops the torrent when seed ratio/max upload bytes limit has reached.

i think that this is better approach
