### ISSUE TITLE
How to know path of my torrent files?

### ISSUE THREAD

**Issue by zhulik** [anacrolix/torrent#52]
It's me again=)

I can't find Torrent's method wich allows me to get it's root path.

So, i use helper like this
`path.Join(downloadPath, t.Info().Name)` Where downloadPath is root which i pass to Client, but i'm not sure it is right for all torrents.

Maybe, finction like Torrent.path() that returns actual path should be added?

**Comment by anacrolix** [comment]
That's a good point. There's an issue that there's not necessarily a filesystem path for a given file in a torrent, the data may be stored in some other format. You can access the file data through the torrent if need be. Otherwise the scheme you've described is correct, you can interate through the torrent Files calling Path on each for each and Join with the base path.

**Comment by zhulik** [comment]
Great, thanks!

**Comment by anacrolix** [comment]
If you're keen a simple PR that documents your findings on how to retrieve the file path would be good.
