### ISSUE TITLE
Usage:  Quick example regarding piece backend

### ISSUE THREAD

**Issue by 0x4139** [anacrolix/torrent#58]
Hi, can you give me a quick example on how the piece data backend should work?

**Comment by anacrolix** [comment]
@0x4139 https://gist.github.com/anacrolix/bff29c6bdb585551bc4f

**Comment by anacrolix** [comment]
Do you need more on this?

**Comment by 0x4139** [comment]
I would like to know what kind of backend is the http one?, is something that you custom made or an already open solution, also it would be awesome if you could update the example to be used with the latest version of the api. Thank you!

**Comment by anacrolix** [comment]
It's a custom HTTP based protocol I made that lets you do simple file manipulation using PUT, GET, DELETE, PATCH with HTTP range requests. The storage backend has changed quite a bit since this issue was first opened. Do you specifically need an example with HTTP or do you just want to write your own piece-based storage backend?

**Comment by 0x4139** [comment]
I want to write a custom piece backend, and i need a small
Example
On how to write and read the pieces

**Comment by anacrolix** [comment]
Take a look at one of the in ./storage. There's file, mmap, pieceBased, and bolt backends now. The bolt one is probably pretty good for an all-in-one implementation.
