### ISSUE TITLE
Query parameters in Announce URL not retained

### ISSUE THREAD

**Issue by robaman** [anacrolix/torrent#63]
It looks like the tracker package doesn't include original query parameters from the announce URL in the HTTP announce requests.

For example, a torrent with Announce URL: http://tracker.domain.com/announce?passkey=abc123

This code makes the request look like: http://tracker.domain.com/announce?info_hash=x&peer_id=z

Transmission (http://www.transmissionbt.com/) for example constructs the following announce request:
http://tracker.domain.com/announce?passkey=abc123&info_hash=x&peer_id=z

It retains the parameter passkey in the announce request from the announce url.

A lot of private BT trackers uses this to add a passkey parameter to the announce requests to be able to associate the bittorrent annonce request with a user in the system.

What do you think about this @anacrolix ? You want me to try and get a PR together?

Thanks!

**Comment by anacrolix** [comment]
Yep sounds good. I never though of this, just mix in my announce specific params with the rest rather than clobbering them all. PR would be good. There was a slight change to the tracker API recently, the http and UDP announce implementations don't match how they're used anymore, let me know what you think of that.

**Comment by robaman** [comment]
PR ready at https://github.com/anacrolix/torrent/pull/64
What do you think @anacrolix ?

**Comment by anacrolix** [comment]
Nailed it.

**Comment by robaman** [comment]
Thanks man!
