### ISSUE TITLE
error running handshook webrtc conn

### ISSUE THREAD

**Issue by canoziia** [anacrolix/torrent#716]
I use the following code to download a torrent and seed it, and then try to download it using instant.io or btorrent.xyz.
``` go
package main

import (
	"log"

	"github.com/anacrolix/torrent"
)

func main() {
	cfg := torrent.NewDefaultClientConfig()
	cfg.Seed = true
	c, _ := torrent.NewClient(cfg)
	defer c.Close()
	t, _ := c.AddMagnet("xxx")
	<-t.GotInfo()
	t.DownloadAll()
	c.WaitAll()
	log.Print("ermahgerd, torrent downloaded")
	select {}
}
```
It worked well in a few seconds, then I saw the logs:
``` log
2022-01-28T13:06:00+0000 CRIT  torrent.go:1559: "xxx": error running handshook webrtc conn: main read loop: reading message length: EOF
2022-01-28T13:06:07+0000 CRIT  torrent.go:1559: "xxx": error running handshook webrtc conn: main read loop: reading message length: EOF
```
After that I can't download the torrent via webtorrent.

**Comment by anacrolix** [comment]
Sorry for not addressing this earlier. This line is still logged at a very high priority. It's expected in normal operation. The download failing is more likely due to a lack of peers. Can you provide the infohash, trackers, and possibly the revision of anacrolix/torrent you were using?

**Comment by marcovidonis** [comment]
@anacrolix I'm experiencing a similar issue with the EOF error: I'm writing an app that takes a magnet link and downloads a file via webtorrent, and the code is very similar to canoziia's. I seed the torrent and generate the magnet link with another app based on your package.

When the clients starts getting the torrent info, it starts logging hundreds of EOF errors. The number of logs increases with the file size, so I assume the EOF is thrown when the client reaches the end of each of the pieces.

I wonder, if this is expected behaviour, why is it treated as an error? I've tried changing the client logger config as follows, but it had no effect on the EOF error:
```
clientConfig.Logger = log.Logger.FilterLevel(clientConfig.Logger, log.Critical)
```

I'm using github.com/anacrolix/torrent v1.43.0

**Comment by anacrolix** [comment]
To be clear I plan to fix this. If you have a sample torrent that I can test against (specifically that tickle the webRTC code), I can make the necessary logging fixes.

@marcovidonis I think the FilterLevel method allows messages of that level and higher. This error is reported at the Critical level (it should really be Debug). That's probably the only fix that is needed.
