### ISSUE TITLE
peer-requesting causing slower downloads

### ISSUE THREAD

**Issue by u1f35c** [anacrolix/torrent#733]
Hi.

We've just updated from v1.19.2 to v1.14.0, conscious of the fact we were lagging behind upstream. However since doing so we've seen a significant drop in throughput; previously seeing 100Mb/s+ and now (with exactly the same seeder setup) seeing initially ~ 10Mb/s, gradually rising over the course of the download but never breaking 70Mb/s (and still at less than 20Mb/s even 50% of the way through).

It looks like the peer-requesting changes are causing the problem; profiling with Go pprof shows the `heap.Init()` in `torrent.(*Peer).maybeUpdateActualRequestState` is showing up as a major hot spot, with `torrent.(*peerRequests).Less` being the largest piece within that.

At the start requestIndexes has about 300,000 entries in it, and this decreases as the torrent progresses (and speeds up), so it looks like there's a polynomial time issue going on with the algorithm, but it's not immediately clear to me how to improve it.

**Comment by anacrolix** [comment]
Thanks for the report! The peer requesting algorithm is very tricky to get right. There are some more performance improvements on master that are pending extra checks from other users before I make a new release. Could you try master which maintains a btree for piece ordering instead of regenerating each update (should be the heap.Init and peerRequest.Less you refer to) and significantly reduces memory allocations in general. It does require go1.18.

**Comment by u1f35c** [comment]
Unfortunately switching to go1.18 is not trivial for the surrounding code; it's in progress, but not likely to happen soon. I tried pulling the `request-strategy/` changes in locally but didn't see any improvement in speed. While there are a lot of allocations going on they don't seem to be the hot path, and while the btree changes away from the google implementation it doesn't seem to change the number of calls into `getDesiredRequestState`.

I think the issue is around building a list of pieces vs building a list of chunks. `getDesiredRequestState` expands every piece into all of its chunks and pushes them all on the requestHeap, which is then the thing that ends up sorted and compared with other peers. In the instance I'm seeing there are 1025 pieces that then have 320 chunks each, so that's why we see over 300,000 entries in the list. Additionally this is a situation where there are 32 full seeds available with a large amount of bandwidth, so each individual chunk request is completing very quickly and it's the calculation cost that slows things down.

Would it perhaps make more sense to assign pieces per peer first, then only expand the chunks once the peer is assigned? Or assign only a piece at a time and calculate chunk requests from that single piece instead of all of them? It's still a quadratic function but with a much smaller input size which should improve performance dramatically.

**Comment by anacrolix** [comment]
Do you want to try removing the peakRequests part from https://github.com/anacrolix/torrent/blob/32501740f2f9e69af4e4ece37aeb4499cd8dc8a9/peerconn.go#L500? Another thing is to set https://github.com/anacrolix/torrent/blob/c6ee03f449fa82d0fd6ba06d6bdb7c5062b38d28/config.go#L63 to something non-zero, something like 32MiB.

**Comment by u1f35c** [comment]
Tweaking the `maxRequests` line doesn't make a noticeable difference, but setting MaxUnverifiedBytes in the client to 64M causes a decent improvement - though still roughly half the overall average speed that was seen with the old version and 20% of CPU time spent in functions under `maybeUpdateActualRequestState`.

**Comment by anacrolix** [comment]
If you can share the particular torrent that triggers the condition for you, or PM/email it to me if necessary, that would help a lot.

**Comment by anacrolix** [comment]
My usage of anacrolix/torrent is mainly with a cache, which heavily restricts how much the client looks forward for possible requests to make. So if you have a storage with no capacity (regular files/mmap etc.), and a very large torrent and many peers, they will be looking over huge windows of requests per your description of the bad behaviour. Earlier variations of the request strategies made compromises and allowed a lot of overlap/randomness in request patterns. The latest attempt that's currently in use tries very hard to reduce wasteful downloads. There are a trail of issues with the variosu attempts, https://github.com/anacrolix/torrent/issues/698, and https://github.com/anacrolix/torrent/issues/634 for example.

**Comment by u1f35c** [comment]
Unfortunately it's not easy for me to share the torrent in question as it's internally generated. The infrastructure tries to keep it at about 1024 pieces and it's about 5.5G in size; I'll see if I can extract any further info about it that might be helpful. Bumping MaxUnverifiedBytes has improved things such that we're ok for the moment and work is in progress to move to go1.18 at which point I'll poke master properly to see how things look there.

**Comment by anacrolix** [comment]
Thanks for the feedback! If you have more insight into the requesting algorithm let me know. It doesn't have a piece-allocator, due to the desire to make the torrent Readers responsive. I looked into the possibility of not building the request heap for cases where there's no prioritization or overlap of requests (very large torrents with very flat prioritization), but it didn't look possible with the current design due to how request ordering works: supporting stealing, retaining existing requests, factoring in piece availability etc. I don't think is trivial in these cases. There could be corner cases that are optimized.

A huge upcoming optimization that should be available is using generics for the request heap. I don't know of a generic heap implementation yet, but the overhead there is probably huge. There was already an enormous saving in the piece ordering by making use of generics.

**Comment by AskAlexSharov** [comment]
@u1f35c hi. `20% of CPU time spent in functions under maybeUpdateActualRequestState` - recently found one way to reduce CPU usage in this func: https://github.com/anacrolix/torrent/discussions/741#discussioncomment-2685458
need increase TorrentSpec.ChunkSize to `128 * 1024`. But I don't know - will it somehow reduce network efficiency or not (on my simple tests it works good).

**Comment by anacrolix** [comment]
Yeah my comment there about congestion is only an observation. If it works for you, don't sweat it.

**Comment by anacrolix** [comment]
@u1f35c This should be fixed in v1.43.0. Please report back your experience with it.
