### ISSUE TITLE
cannot call pointer method Int64 on torrent.Count

### ISSUE THREAD

**Issue by glblduh** [anacrolix/torrent#745]
The error occurs when I try to get the int64 value of BytesRead with `Stats().BytesRead.Int64()`

**Comment by anacrolix** [comment]
This is an oddity that exists because of atomics. Count.Int64 has a pointer receive so it can do an atomic operation on the correct memory address. However Torrent.Stats returns a value copy of the ConnStats, which don't have an address until you assign it. You can work around it with `stats := Torrent.Stats(); stats.BytesRead.Int64()`. The better fix might be to not use atomics for these values, but I think it was added because the Client lock and other locks are fairly coarse in this package.

**Comment by glblduh** [comment]
Thanks, the work around fixed the issue.
