### ISSUE TITLE
bencode doesn't throw error for invalid torrent

### ISSUE THREAD

**Issue by trim21** [anacrolix/torrent#963]
content of `flat-url-list.torrent` and `trackerless.torrent` are not valid bencode encoded data and bencode didn't return error for these 2 torrent. they have extra `\n` at end of file which is not allowed.

**Comment by anacrolix** [comment]
What function did you unmarshal your metainfos with? It may be using an older API that doesn't check for trailing bytes.

**Comment by trim21** [comment]
https://github.com/anacrolix/torrent/blob/02fe1a9a0b69a141c07344ef0abf93c5b94899f8/metainfo/metainfo_test.go#L20 this one

**Comment by anacrolix** [comment]
Good catch. LoadFromFile incorrectly ignores trailing data because it calls Decoder.Decode and doesn't check for EOF. (Unmarshal does this, but isn't well suited to reading from an io.Reader). The tests should be fixed to detect the incorrect handling, but also to catch and error on trailing bytes for LoadFromFile.

**Comment by anacrolix** [comment]
Decoder.Decode should correctly return io.EOF if there's a clean message boundary. So LoadFromFile should use that since it's expected that metainfo/torrent files end cleanly. That said, there's probably a certain amount of leeway that should be supported, since metainfos aren't hashed anywhere and aren't required to be byte-perfect I think.

**Comment by trim21** [comment]
I don't think `Decoder.Decode` should return err if expected `io.EOF` returned from reader. for example, `encoding/json` doesn't return a `io.EOF` at end of reader, and a `io.EOF` is expected to be read from reader, it's not a unmarshal error.

**Comment by anacrolix** [comment]
@trim21 thanks for spotting this. I've pushed a fix. It might be a tad pedantic but lets see how it goes.
